onspar/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^portfolio/', include('portfolio.urls')),
    url(r'', include('portfolio.urls', namespace='portfolio')),
# Shop App URLs
    # Below is likely URL but will need to update
    url(r'^shop/', include('shop.urls', namespace='shop')),
]


#if settings.DEBUG:
 #   urlpatterns += static(settings.MEDIA_URL,
  #                        document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.conf.urls import url
from . import views

from django.contrib.auth.views import login
from django.contrib.auth.views import logout
from django.contrib.auth.views import logout_then_login
from django.contrib.auth.views import password_change
from django.contrib.auth.views import password_change_done
from django.contrib.auth.views import password_reset
from django.contrib.auth.views import password_reset_done
from django.contrib.auth.views import password_reset_confirm
from django.contrib.auth.views import password_reset_complete

app_name='portfolio'

urlpatterns = [

    url(r'^$', views.home, name='home'),
    url(r'^home/$', views.home, name='home'),
   # url(r'^notifications/$', views.notifications, name='notifications'),
    #url(r'^signup/$',views.signup,name='signup'),
    url(r'^employee/$', views.employee_list, name='employee_list'),
    url(r'^employee/(?P<pk>\d+)/delete/$', views.employee_delete, name='employee_delete'),
    url(r'^employee/(?P<pk>\d+)/edit/$', views.employee_edit, name='employee_edit'),
    url(r'^employee/create/$', views.employee_new, name='employee_new'),
    url(r'^account_settings_list/$', views.account_settings_list, name='account_settings_list'),
    url(r'^register/$', views.register, name='register'),
    url(r'^account/register/$', views.register, name='register'),
    # previous login view
    # url(r'^login/$', views.user_login, name='login'),

    # login / logout urls
    url(r'^login/$',
        login,
        name='login'),
    url(r'^logout/$',
        logout,
        name='logout'),
    url(r'^logout-then-login/$',
        logout_then_login,
        name='logout_then_login'),


    # change password urls
    url(r'^password-change/$',
        password_change,
        name='password_change_form'),
    url(r'^password-change/done/$',
        password_change_done,
        name='password_change_done'),

# restore password urls
    url(r'^password-reset/$',
        password_reset,
        name='password_reset'),
    url(r'^password-reset/done/$',
        password_reset_done,
        name='password_reset_done'),
    url(r'^password-reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$',
        password_reset_confirm,
        name='password_reset_confirm'),
    url(r'^password-reset/complete/$',
        password_reset_complete,
        name='password_reset_complete'),



]

shop/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
        url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
        url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
        #Root url
        url(r'^$', views.product_list, name='product_list'),
        ]

portfolio/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class Employee(models.Model):
    emp_number = models.IntegerField(blank=False, null=False)
    name = models.CharField(max_length=50)
    address = models.CharField(max_length=200)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    zipcode = models.IntegerField(blank=False, null=False)
    email = models.EmailField(max_length=200)
    cell_phone = models.IntegerField(blank=False, null=False)
    created_date = models.DateTimeField(default=timezone.now)
    updated_date = models.DateTimeField(auto_now_add=True)


    def created(self):
        self.recent_date = timezone.now()
        self.save()

    def updated(self):
        self.updated_date = timezone.now()
        self.save()

    def __str__(self):
        return str(self.emp_number)

portfolio/forms.py
from django import forms
from .models import Employee
from django.contrib.auth.models import User


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password',
                               widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password',
                                widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']

class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = ('name', 'address', 'emp_number', 'city', 'state', 'zipcode', 'email', 'cell_phone',)

portfolio/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import authenticate, login
from .forms import LoginForm, UserRegistrationForm
from django.contrib.auth.decorators import login_required

from .models import *
from django.shortcuts import render, get_object_or_404
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from .forms import *
from django.db.models import Sum

from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views
#from shop.models import Product


@login_required
def home(request):
    return render(request,
                  'portfolio/home.html',
                  {'section': 'home'})

# User Login Methods SAVE!!!
'''
def notifications(request):
    products = Product.objects.all()
    requireRestock = []
    for product in products:
        if (product.stock <= 20):
            requireRestock.append(product)
    return render(request,'portfolio/notifications.html',{'notifications': requireRestock})
'''
def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd['username'],
                                password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponse('Authenticated '\
                                        'successfully')
                else:
                    return HttpResponse('Disabled account')
            else:
                return HttpResponse('Invalid login')
    else:
        form = LoginForm()
    return render(request, 'portfolio/login.html', {'form': form})

def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            # Create a new user object but avoid saving it yet
            new_user = user_form.save(commit=False)
            # Set the chosen password
            new_user.set_password(
                user_form.cleaned_data['password'])
            # Save the User object
            new_user.save()
            return render(request,
                          'account/register_done.html',
                          {'new_user': new_user})
    else:
        user_form = UserRegistrationForm()
    return render(request,
                  'account/register.html',
                  {'user_form': user_form})
# Employee CRUD Methods

@login_required
def employee_list(request):
    employees = Employee.objects.filter(created_date__lte=timezone.now())
    return render(request, 'portfolio/employee_list.html', {'employees': employees})


@login_required
def employee_new(request):
   if request.method == "POST":
       form = EmployeeForm(request.POST)
       if form.is_valid():
           employee = form.save(commit=False)
           employee.created_date = timezone.now()
           employee.save()
           employees = Employee.objects.filter(created_date__lte=timezone.now())
           return render(request, 'portfolio/employee_list.html',
                         {'employees': employees})
   else:
       form = EmployeeForm()
       # print("Else")
   return render(request, 'portfolio/employee_new.html', {'form': form})


@login_required
def employee_edit(request, pk):
    employee = get_object_or_404(Employee, pk=pk)
    if request.method == "POST":
       # update
        form = EmployeeForm(request.POST, instance=employee)
        if form.is_valid():
            employee = form.save(commit=False)
            employee.updated_date = timezone.now()
            employee.save()
            employees = Client.objects.filter(created_date__lte=timezone.now())
            return render(request, 'portfolio/employee_list.html',
                         {'employees': employees})
    else:
               # edit
            form = EmployeeForm(instance=employee)
            return render(request, 'portfolio/employee_edit.html', {'form': form})


@login_required
def employee_delete(request, pk):
    employee = get_object_or_404(Employee, pk=pk)
    employee.delete()
    employees = Employee.objects.filter(created_date__lte=timezone.now())
    return render(request, 'portfolio/employee_list.html', {'employees': employees})


@login_required
def account_settings_list(request):
    return render(request,
                  'portfolio/account_settings_list.html',
                  {'section': 'account_settings_list'})

@login_required
def password_change_form(request):
    return render(request,
                  'registration/password_change_form.html',
                  {'section': 'password_change_form'})

@login_required
def password_change_done(request):
    return render(request,
                  'registration/password_change_done.html',
                  {'section': 'password_change_done'})

portfolio/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Good Shepherd Food Pantry</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    <style>
        /* Remove the navbar's default margin-bottom and rounded borders */
        .navbar {
{#            margin-bottom: 0;#}
            border-radius: 0;
            font-family: 'Raleway', sans-serif;
{#            background-color:#D2EAFA;#}
            font-size: 1.3em !important;
{#            font-weight: bold;#}
        }
        p,h2,h1{
             font-family: 'Raleway', sans-serif;
             font-size: 1.5em !important;
        }
        label{
             font-family: 'Raleway', sans-serif;
             font-size: 15px !important;
        }

        /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
        .row.content {
            height: 450px
        }

        /* Set gray background color and 100% height */
        .sidenav {
            padding-top: 20px;
            background-color: red;
            height: 100%;
        }

        /* Set black background color, white text and some padding */
        footer {
            background-color: #777;
            color: white;
            padding: 15px;
        }

        /* On small screens, set height to 'auto' for sidenav and grid */
        @media screen and (max-width: 767px) {
            .sidenav {
                height: auto;
                padding: 15px;
            }

            .row.content {
                height: auto;
            }
        }
    </style>
</head>

<body id="app-layout" style="background-color:#c9c9c9 ">
<div class="content container">
    <div class="row">
        <div class="col-md-10">
            {% block content %}
                <div class="links">
                    <!-- Example row of columns -->
                    <div class="row">


                      <div class="col-md-3">
                          <div class="thumbnail">
                              <img src="{% static "images/client.jpg" %}" alt="Client"/>
                              <div class="caption">
                                  <h2>Clients</h2>
                                  <p>Add, edit, or delete clients</p>
                                  {% if user.is_authenticated %}
                                      <p><a class="btn btn-default" href="#"
                                            role="button">View
                                          details &raquo;</a></p>
                                  {% endif %}
                              </div>
                          </div>
                      </div>

                      <div class="col-md-3">
                          <div class="thumbnail">
                              <img src="{% static "images/visit.jpg" %}" alt="Visits"/>
                              <div class="caption">
                                  <h2>Visits</h2>
                                  <p>Add, edit, or delete visits</p>
                                  <p><a class="btn btn-default" href="#"
                                         role="button">View
                                      details &raquo;</a></p>
                              </div>
                          </div>
                        </div>

                <!--      <div class="col-md-3">
                          <div class="thumbnail">
                              <img src="{% static "images/shop.jpg" %}" alt="Shop"/>
                              <div class="caption">
                                  <h2>Shop</h2>
                                  <p>Browse current inventory</p>
                                  <p><a class="btn btn-default" href="{% url "shop:product_list" %}"
                                         role="button">View
                                      details &raquo;</a></p>
                              </div>
                          </div>
                        </div>
-->
                      <div class="col-md-3">
                            <div class="thumbnail">
                                <img src="{% static "images/cart.jpg" %}" alt="Cart"/>
                                <div class="caption">
                                    <h2>Cart</h2>
                                    <p>Review selected products</p>
                                    <p><a class="btn btn-default" href="#"
                                           role="button">View
                                        details &raquo;</a></p>
                                </div>
                            </div>
                          </div>

                          <div class="col-md-3">
                              <div class="thumbnail">
                                  <img src="{% static "images/checkout.jpg" %}" alt="Checkout"/>
                                  <div class="caption">
                                      <h2>Checkout</h2>
                                      <p>Inventory Management</p>
                                      <p><a class="btn btn-default" href="#"
                                             role="button">View
                                          details &raquo;</a></p>
                                  </div>
                              </div>
                            </div>

                      <div class="col-md-3">
                          <div class="thumbnail">
                              <img src="{% static "images/employees.jpg" %}" alt="Employee"/>
                              <div class="caption">
                                  <h2>Employees</h2>
                                  <p>View food pantry employees</p>
                                  <p><a class="btn btn-default" href="#"
                                         role="button">View
                                      details &raquo;</a></p>
                              </div>
                          </div>
                      </div>
                      <div class="col-md-3">
                          <div class="thumbnail">
                              <img src="{% static "images/donor.jpg" %}" alt="Donor"/>
                              <div class="caption">
                                  <h2>Donors</h2>
                                  <p>View food pantry donors</p>
                                  <p><a class="btn btn-default" href="#" role="button">View
                                      details &raquo;</a></p>
                              </div>
                          </div>
                      </div>
                      <div class="col-md-3">
                          <div class="thumbnail">
                              <img src="{% static "images/setting.jpg" %}" alt="Settings"/>
                              <div class="caption">
                                  <h2>Settings</h2>
                                  <p>Edit account settings</p>
                                  <p><a class="btn btn-default" href="{% url 'portfolio:account_settings_list' %}"
                                         role="button">View
                                      details &raquo;</a></p>
                              </div>
                          </div>
                        </div>


                    </div>
                </div>
            {% endblock %}
        </div>
    </div>
</body>
</html>

portfolio/templates/old_base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Good Shepherd Food Pantry</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <link rel="stylesheet" href="../css/fullwidth.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style>
        /* Remove the navbar's default margin-bottom and rounded borders */
        .navbar {
            margin-bottom: 0;
            border-radius: 0;
            background-color:#D2EAFA;
            font-size: 1.3em !important;
            font-weight: bold;
        }

        /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
        .row.content {
            height: 450px
        }

        /* Set gray background color and 100% height */
        .sidenav {
            padding-top: 20px;
            background-color: red;
            height: 100%;
        }

        /* Set black background color, white text and some padding */
        footer {
            background-color: #777;
            color: white;
            padding: 15px;
        }

        /* On small screens, set height to 'auto' for sidenav and grid */
        @media screen and (max-width: 767px) {
            .sidenav {
                height: auto;
                padding: 15px;
            }

            .row.content {
                height: auto;
            }
        }
    </style>
</head>

<body id="app-layout">
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">

            <!-- Collapsed Hamburger -->
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#myNavbar">



                <span class="sr-only">Toggle Navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <!-- Branding Image -->

        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'portfolio:home' %}">Home</a></li>
                <li><a href="{% url 'portfolio:client_list' %}">Clients</a></li>
                <li><a href="{% url 'portfolio:visit_list' %}">Visits</a></li>
                <li><a href="{% url "shop:product_list" %}">Shop</a></li>
                <li><a href="{% url "cart:cart_detail" %}">Cart</a></li>
                <li><a href="{% url "orders:order_create" %}">Checkout</a></li>
                <!-- <li><a href="{% url 'portfolio:item_list' %}">Inventory</a></li> -->
                <li><a href="{% url 'portfolio:employee_list' %}">Employees</a></li>
                <li><a href="{% url 'portfolio:donor_list' %}">Donors</a></li>
                <li><a href="{% url 'portfolio:account_settings_list' %}">Account Settings</a></li>
                <li>
                  <a href="{% url "logout" %}">Logout</a>
                </li>
            </ul>

        </div>
    </div>
</nav>
<div class="content container">
    <div class="row">
        <div class="col-md-10">
            {% block content %}
                <div class="links">
                    <!-- Example row of columns -->
                    <div class="row">


                      <div class="col-md-3">
                          <div class="thumbnail">
                              <img src="{% static "images/client.jpg" %}" alt="Client"/>
                              <div class="caption">
                                  <h2>Clients</h2>
                                  <p>Add, edit, or delete clients</p>
                                  {% if user.is_authenticated %}
                                      <p><a class="btn btn-default" href="{% url 'portfolio:client_list' %}"
                                            role="button">View
                                          details &raquo;</a></p>
                                  {% endif %}
                              </div>
                          </div>
                      </div>

                      <div class="col-md-3">
                          <div class="thumbnail">
                              <img src="{% static "images/visit.jpg" %}" alt="Visits"/>
                              <div class="caption">
                                  <h2>Visits</h2>
                                  <p>Add, edit, or delete visits</p>
                                  <p><a class="btn btn-default" href="{% url 'portfolio:visit_list' %}"
                                         role="button">View
                                      details &raquo;</a></p>
                              </div>
                          </div>
                        </div>

                      <div class="col-md-3">
                          <div class="thumbnail">
                              <img src="{% static "images/shop.jpg" %}" alt="Shop"/>
                              <div class="caption">
                                  <h2>Shop</h2>
                                  <p>Browse current inventory</p>
                                  <p><a class="btn btn-default" href="{% url "shop:product_list" %}"
                                         role="button">View
                                      details &raquo;</a></p>
                              </div>
                          </div>
                        </div>

                        <div class="col-md-3">
                            <div class="thumbnail">
                                <img src="{% static "images/cart.jpg" %}" alt="Cart"/>
                                <div class="caption">
                                    <h2>Cart</h2>
                                    <p>Review selected products</p>
                                    <p><a class="btn btn-default" href="{% url "cart:cart_detail" %}"
                                           role="button">View
                                        details &raquo;</a></p>
                                </div>
                            </div>
                          </div>

                          <div class="col-md-3">
                              <div class="thumbnail">
                                  <img src="{% static "images/checkout.jpg" %}" alt="Checkout"/>
                                  <div class="caption">
                                      <h2>Checkout</h2>
                                      <p>Inventory Management</p>
                                      <p><a class="btn btn-default" href="{% url "orders:order_create" %}"
                                             role="button">View
                                          details &raquo;</a></p>
                                  </div>
                              </div>
                            </div>

                      <div class="col-md-3">
                          <div class="thumbnail">
                              <img src="{% static "images/employees.jpg" %}" alt="Employee"/>
                              <div class="caption">
                                  <h2>Employees</h2>
                                  <p>View food pantry employees</p>
                                  <p><a class="btn btn-default" href="{% url 'portfolio:employee_list' %}"
                                         role="button">View
                                      details &raquo;</a></p>
                              </div>
                          </div>
                      </div>
                      <div class="col-md-3">
                          <div class="thumbnail">
                              <img src="{% static "images/donor.jpg" %}" alt="Donor"/>
                              <div class="caption">
                                  <h2>Donors</h2>
                                  <p>View food pantry donors</p>
                                  <p><a class="btn btn-default" href="{% url 'portfolio:donor_list' %}" role="button">View
                                      details &raquo;</a></p>
                              </div>
                          </div>
                      </div>
                      <div class="col-md-3">
                          <div class="thumbnail">
                              <img src="{% static "images/setting.jpg" %}" alt="Account Settings"/>
                              <div class="caption">
                                  <h2>Settings</h2>
                                  <p>Edit account settings</p>
                                  <p><a class="btn btn-default" href="{% url 'portfolio:account_settings_list' %}"
                                         role="button">View
                                      details &raquo;</a></p>
                              </div>
                          </div>
                        </div>


                    </div>
                </div>
            {% endblock %}
        </div>
    </div>
</body>
</html>